export enum MediaVariantType {
  OPTIMIZED_IMAGE = 'OPTIMIZED_IMAGE',
  IMAGE_THUMBNAIL = 'IMAGE_THUMBNAIL',
  NORMALIZED_AUDIO = 'NORMALIZED_AUDIO',
  VIDEO_360P = 'VIDEO_360P',
  VIDEO_720P = 'VIDEO_720P',
  VIDEO_1080P = 'VIDEO_1080P',
  VIDEO_SOURCE = 'VIDEO_SOURCE',
  VIDEO_THUMBNAIL = 'VIDEO_THUMBNAIL',
}
