export enum PostAggregateStatus {
  NO_MEDIA = 'NO_MEDIA',
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  PARTIALLY_COMPLETED = 'PARTIALLY_COMPLETED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}
