export enum ProcessingStep {
  PENDING = 'PENDING',
  CLAIMING = 'CLAIMING',
  DOWNLOADING = 'DOWNLOADING',
  VERIFYING = 'VERIFYING',
  PROBING = 'PROBING',
  PLANNING = 'PLANNING',
  PROCESSING = 'PROCESSING',
  UPLOADING = 'UPLOADING',
  FINALIZING = 'FINALIZING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}
